spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tweeterdb
    username: tweeter
    password: tweeter123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: # leave empty if no password
      database: 0

camel:
  springboot:
    main-run-controller: true
  component:
    kafka:
      brokers: localhost:9092
      auto-offset-reset: earliest
      group-id: tweet-processor-group

kafka:
  topic:
    tweeter-source: twitter-feed-topic

server:
  port: 8081

logging:
  level:
    root: INFO
    com.test.twt.source: DEBUG
    org.hibernate.SQL: DEBUG
